[package]
name = "ldn_mitm_rs"
version = "0.1.0"
authors = ["spacemeowx2"]
edition = "2018"

[dependencies]
nx = { git = "https://github.com/spacemeowx2/nx", rev = "bb0dbf11d5ca4332b9a1322597a3b78808e353f2" }
paste = "1.0"

[package.metadata.nx.nsp]
npdm = "npdm.json"
